In [30]:
import pandas as pd

df_um5 = pd.read_csv('interactions.csv', header=None)

In [2]:
df_um5.head()

0  1  2  3  4
0  0  0  0  0  0
1  0  1  0  0  0
2  1  0  1  0  0
3  1  0  0  1  0
4  1  0  0  1  0

In [3]:
df_um5.rename(columns={0: "action", 1: "interaction", 2:"prev_success", 3: "prev_action", 4: "pain"}, inplace=True)
df_um5.head()

action  interaction  prev_success  prev_action  pain
0       0            0             0            0     0
1       0            1             0            0     0
2       1            0             1            0     0
3       1            0             0            1     0
4       1            0             0            1     0

In [4]:
df_um5.groupby(['action'])['interaction'].describe()

count      mean       std  min  25%  50%  75%  max
action                                                    
0        29.0  0.275862  0.454859  0.0  0.0  0.0  1.0  1.0
1        30.0  0.200000  0.406838  0.0  0.0  0.0  0.0  1.0
2        30.0  0.300000  0.466092  0.0  0.0  0.0  1.0  1.0
3        30.0  0.500000  0.508548  0.0  0.0  0.5  1.0  1.0
4        31.0  0.548387  0.505879  0.0  0.0  1.0  1.0  1.0
5        30.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0

In [5]:
df_um5.groupby([ "action", "prev_success"]).mean()

interaction  prev_action  pain
action prev_success                                
0      0                0.190476     0.857143   0.0
       1                0.500000     0.875000   0.0
1      0                0.100000     1.650000   0.0
       1                0.400000     1.500000   0.0
2      0                0.181818     2.181818   0.0
       1                0.625000     2.250000   0.0
3      0                0.294118     2.705882   0.0
       1                0.769231     2.923077   0.0
4      0                0.473684     3.105263   0.0
       1                0.666667     4.000000   0.0
5      0                0.000000     4.185185   0.0
       1                0.000000     2.333333   0.0

# Train model

In [6]:
def createdf(file, um):
    df = pd.read_csv(file, header=None)
    df.rename(columns={0: "action", 1: "interaction", 2:"prev_success", 3: "prev_action", 4: "pain"}, inplace=True)
    df['um']=um
    return df

df_um1= createdf('interactions_um1.csv', 1)
df_um2= createdf('interactions_um2.csv', 2)
df_um3= createdf('interactions_um3.csv', 3)
df_um4= createdf('interactions_um4.csv', 4)
frames = [df_um1, df_um2, df_um3, df_um4]

df_ums = pd.concat(frames)
# df_ums.drop(["1"], axis=1, inplace=True)
# df_ums.dropna(inplace=True)
df_ums.head()

action  interaction  prev_success  prev_action  pain  um
0       0            0             0            0     0   1
1       0            0             0            0     0   1
2       0            0             0            0     0   1
3       0            0             0            0     0   1
4       0            0             0            0     0   1

In [7]:
df_ums.groupby(["um", "action", "prev_success"]).mean()

interaction  prev_action  pain
um action prev_success                                
1  0      0                0.019875     0.000630   0.0
          1                0.598170     0.004926   0.0
   1      0                0.041613     1.000645   0.0
          1                0.700437     1.000273   0.0
   2      0                0.120009     2.000298   0.0
          1                0.903113     2.000121   0.0
   3      0                0.056860     2.999775   0.0
          1                0.550845     3.000000   0.0
   4      0                0.132570     3.999179   0.0
          1                0.793850     3.999830   0.0
   5      0                0.020473     4.999077   0.0
          1                0.191375     4.995957   0.0
2  0      0                0.098278     0.000881   0.0
          1                0.693743     0.000686   0.0
   1      0                0.142652     1.000633   0.0
          1                0.803329     1.000555   0.0
   2      0                0.141749     2.000320   0.0
          1                0.898754     2.000114   0.0
   3      0                0.162004     2.999669   0.0
          1                0.752968     3.000000   0.0
   4      0                0.177674     3.999371   0.0
          1                0.605452     3.999571   0.0
   5      0                0.076758     4.999363   0.0
          1                0.606129     4.997140   0.0
3  0      0                0.021060     0.000870   0.0
          1                0.523997     0.000000   0.0
   1      0                0.019856     1.000631   0.0
          1                0.621405     1.000000   0.0
   2      0                0.080613     2.000160   0.0
          1                0.603435     2.000395   0.0
   3      0                0.040556     2.999822   0.0
          1                0.420865     2.999491   0.0
   4      0                0.068720     3.999335   0.0
          1                0.602625     4.000000   0.0
   5      0                0.020596     4.999076   0.0
          1                0.217899     4.996109   0.0
4  0      0                0.010350     0.000683   0.0
          1                0.577931     0.006897   0.0
   1      0                0.029300     1.000654   0.0
          1                0.809917     1.000250   0.0
   2      0                0.108743     2.000481   0.0
          1                0.898007     1.999935   0.0
   3      0                0.040581     2.999928   0.0
          1                0.446984     2.998054   0.0
   4      0                0.019785     3.999557   0.0
          1                0.083465     3.993701   0.0
   5      0                0.019768     4.999106   0.0
          1                0.369113     4.995619   0.0

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
X = df_ums.iloc[:,:-1]
y = df_ums.iloc[:, -1:]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
print(X_train.isnull())


        action  interaction  prev_success  prev_action   pain
142234   False        False         False        False  False
77696    False        False         False        False  False
177409   False        False         False        False  False
11260    False        False         False        False  False
74179    False        False         False        False  False
...        ...          ...           ...          ...    ...
79178    False        False         False        False  False
5838     False        False         False        False  False
131932   False        False         False        False  False
131155   False        False         False        False  False
121958   False        False         False        False  False

[576000 rows x 5 columns]


In [10]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)


C:\ProgramData\Anaconda3\envs\py\lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [11]:
knn.score(X_test, y_test)

0.29311805555555553

# Episodic data


In [12]:
import pandas as pd
import ast  # Import the ast module to convert strings to lists

# Function to concatenate values in each row without square brackets
def concatenate_values(row):
    return ','.join(map(str, sum(map(ast.literal_eval, row), [])))




In [13]:
def createdf(file, um):
    df = pd.read_csv(file, header=None)
    df['combined'] = df.apply(concatenate_values, axis=1)
    df = df.drop(columns=df.columns.difference(['combined'])) 
    # Split the values in the 'combined' column
    split_values = df['combined'].str.split(',', expand=True)

    # Concatenate the split values with the original DataFrame
    df = pd.concat([df, split_values], axis=1)
    df = df.drop(["combined"], axis=1) 

    df['um']=um
    return df

dfe_um1= createdf('interactions_um1_episodes.csv', 1)
dfe_um2= createdf('interactions_um2_episodes.csv', 2)
dfe_um3= createdf('interactions_um3_episodes.csv', 3)
dfe_um4= createdf('interactions_um4_episodes.csv', 4)
frames = [dfe_um1, dfe_um2, dfe_um3, dfe_um4]

dfe_ums = pd.concat(frames)
# dfe_ums.drop(["1"], axis=1, inplace=True)
# dfe_ums.dropna(inplace=True)
dfe_ums.head()

0  1  2  3  4  5  6  7  8  9  ... 891 892 893 894 895 896 897 898 899 um
0  0  0  0  0  0  0  0  0  0  0  ...   0   0   5   0   4   0   0   5   0  1
1  0  0  0  0  0  0  0  0  0  0  ...   0   0   5   0   4   1   0   5   0  1
2  0  0  0  0  0  0  0  0  0  0  ...   0   0   5   0   4   0   0   5   0  1
3  0  0  0  0  0  0  0  0  0  0  ...   0   0   5   0   4   1   0   5   0  1
4  0  0  0  0  0  0  0  0  0  0  ...   0   0   5   0   4   1   0   5   0  1

[5 rows x 901 columns]

In [14]:
Xe = dfe_ums.iloc[:,:-1]
ye = dfe_ums.iloc[:, -1:]
Xe_train, Xe_test, ye_train, ye_test = train_test_split(Xe, ye, test_size=0.2, random_state=42)

In [15]:
Xe_test.head()

0   1   2   3   4   5   6   7   8   9    ... 890 891 892 893 894 895 896  \
555   0   0   0   0   0   0   0   0   0   0  ...   5   0   0   5   0   4   1   
491   0   0   0   0   0   0   0   0   0   0  ...   5   0   0   5   0   4   0   
527   0   0   0   0   0   0   0   0   0   0  ...   5   0   0   5   0   4   1   
925   0   0   0   0   0   0   0   0   0   0  ...   5   0   0   5   0   4   0   
989   0   0   0   0   0   0   0   0   0   0  ...   5   0   0   5   0   4   0   

    897 898 899  
555   0   5   0  
491   0   5   0  
527   0   5   0  
925   0   5   0  
989   0   5   0  

[5 rows x 900 columns]

In [37]:
knn_e = KNeighborsClassifier(n_neighbors=5)
knn_e.fit(Xe_train, ye_train)

C:\ProgramData\Anaconda3\envs\py\lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [38]:
knn_e.score(Xe_test.values, ye_test)

0.82375

In [18]:
y_pred = knn_e.predict(Xe_test.values)

In [19]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(ye_test, y_pred))

[[144   0  35  30]
 [ 18 193   0   2]
 [  7   0 130  57]
 [  0   0   1 183]]


# Test on user model 5

In [20]:
dfe_um5= createdf('interactions_um5_episodes.csv', 5)
dfe_um5.drop(["um"], axis =1, inplace=True)
dfe_um5.head()

0   1   2   3   4   5   6   7   8   9    ... 890 891 892 893 894 895 896  \
0   0   0   0   0   0   0   0   0   0   0  ...   5   0   0   5   0   4   1   

  897 898 899  
0   0   5   0  

[1 rows x 900 columns]

In [21]:
pred = knn_e.predict(dfe_um5.values)
print(pred[0])

1


# Distance measure

In [22]:
median_df= dfe_ums.groupby(['um']).median()
median_df

0    1    2    3    4    5    6    7    8    9    ...  890  891  892  893  \
um                                                    ...                       
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0  5.0   
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0  5.0   
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0  5.0   
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0  5.0   

    894  895  896  897  898  899  
um                                
1   0.0  4.0  1.0  0.0  5.0  0.0  
2   0.0  4.0  1.0  0.0  5.0  0.0  
3   0.0  4.0  0.0  0.0  5.0  0.0  
4   0.0  4.0  0.0  0.0  5.0  0.0  

[4 rows x 900 columns]

In [23]:
from scipy.spatial.distance import euclidean
import numpy as np
um5= np.array(dfe_um5.iloc[0,:-1]).astype(str).astype(int)
um1= np.array(median_df.iloc[0,:-1]).astype(int)
um2= np.array(median_df.iloc[1,:-1]).astype(int)
um3= np.array(median_df.iloc[2,:-1]).astype(int)
um4= np.array(median_df.iloc[3,:-1]).astype(int)



In [24]:
d_to_um1 = euclidean(um5, um1)
d_to_um2 = euclidean(um5, um2)
d_to_um3 = euclidean(um5, um3)
d_to_um4 = euclidean(um5, um4)
print("Distance to um1: %2d; distance to um2: %2d; distance to um3: %2d; distance to um4:%2d" %(d_to_um1, d_to_um2,d_to_um3, d_to_um4))

Distance to um1: 11; distance to um2: 12; distance to um3: 12; distance to um4:11


In [25]:
from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('euclidean')
dist.pairwise([um1, um2, um3, um4, um5])

array([[ 0.        , 12.88409873, 11.        ,  7.54983444, 11.22497216],
       [12.88409873,  0.        , 15.19868415, 12.92284798, 12.80624847],
       [11.        , 15.19868415,  0.        ,  8.        , 12.12435565],
       [ 7.54983444, 12.92284798,  8.        ,  0.        , 11.95826074],
       [11.22497216, 12.80624847, 12.12435565, 11.95826074,  0.        ]])

In [26]:
dist = DistanceMetric.get_metric('manhattan')
dist.pairwise([um1, um2, um3, um4, um5])

array([[  0., 166., 121.,  57., 126.],
       [166.,   0., 231., 167., 164.],
       [121., 231.,   0.,  64., 147.],
       [ 57., 167.,  64.,   0., 143.],
       [126., 164., 147., 143.,   0.]])

In [27]:
m1= df_um1.groupby(["action", "prev_success"])['interaction'].mean().to_numpy()
m2= df_um2.groupby(["action", "prev_success"])['interaction'].mean().to_numpy()
m3= df_um3.groupby(["action", "prev_success"])['interaction'].mean().to_numpy()
m4= df_um4.groupby(["action", "prev_success"])['interaction'].mean().to_numpy()


In [28]:
m5= df_um5.groupby(["action", "prev_success"])['interaction'].mean().to_numpy()


In [29]:
dist = DistanceMetric.get_metric('euclidean')
dist.pairwise([m1, m2, m3, m4, m5])

array([[0.        , 0.54881168, 0.40260331, 0.75683663, 0.69795553],
       [0.54881168, 0.        , 0.68168913, 0.70733277, 0.87718237],
       [0.40260331, 0.68168913, 0.        , 0.64937251, 0.70504019],
       [0.75683663, 0.70733277, 0.64937251, 0.        , 1.06879827],
       [0.69795553, 0.87718237, 0.70504019, 1.06879827, 0.        ]])